name: CI Pipeline

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  validate_commit_messages:
    uses: woped/devops/.github/workflows/validate-commit-msg.yaml@main
